# Generated by Django 3.1.2 on 2020-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
