# Generated by Django 3.1.2 on 2020-10-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='recipes',
            field=models.ManyToManyField(to='main_app.Recipe'),
        ),
    ]
