# Generated by Django 3.1.2 on 2020-10-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('entree', 'Entree'), ('side', 'Side Dish'), ('sauce', 'Sauce'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='entree', max_length=10),
        ),
    ]
