# Generated by Django 3.1.2 on 2020-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201006_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(default='TBD', max_length=150),
            preserve_default=False,
        ),
    ]
